Feature/template config
kubernauts/tk8 pull request #32
Opened 2018-08-14 20:25 UTC by MuellerMH

Fix Issue #26 
Fix Issue #6 
Fix Issue #12 

Tested with CoreOS, CentOS and Ubuntu.

2018-08-17 02:11 UTC, arush-sal requested changes
Review done. Changes and bug fixes required. Also, please make sure to lint your code through `go vet`.

2018-08-17 02:11 UTC, arush-sal commented on internal/cluster/aws.go
> +	awsAmiID, awsInstanceOS, sshUser := GetDistConfig()
sshUser should only be required from the user through `config.yaml` in case when a custom AMI si being used. For either of `centos`, `coreos` or `ubuntu` we have the pre-defined sshUser name available in `internal/aws/common.go#DistOSMap` which rather should be used here.

2018-08-17 02:11 UTC, arush-sal commented on internal/cluster/aws.go
> +	}
```go
if awsAmiID != "" && sshUser != "" {
    err := exec.Command("sh", "-c", "sed -i \"\" -e 's/${data.aws_ami.distro.id}/"+awsAmiID+"/g' ./kubespray/contrib/terraform/aws/create-infrastructure.tf").Run()
    if err != nil {
        log.Fatal("Cannot replace AMI ID in Infrastructure template", err)
    }
}
```

Above functionality is needed for the Custom-AMI implementation. The same can be introduced here as an `else` condition.

2018-08-17 02:11 UTC, arush-sal commented on config.yaml.example
> +   os: ubuntu
Ubuntu as an OS won't work here as the latest AMI of Ubuntu doesn't meet the required prerequisites of Kubespray.
![screen shot 2018-08-17 at 5 47 56 am](https://user-images.githubusercontent.com/8846519/44241374-27aa8400-a1e1-11e8-8c5e-67c17d976c88.png)

2018-08-17 02:11 UTC, arush-sal commented on internal/templates/terraform.go
>      Env = "devtest"
How can the user change these values?

2018-08-17 02:11 UTC, arush-sal commented on internal/cluster/showPath_test.go
> +			want: "/Users/onko/go/src/github.com/kubernauts/tk8/config/test.tpl",
* The config directory doesn't exist, can you please add it?
* Can't have local absolute paths here
* AFAIK referencing a file through its relative path isn't really a good practice and is considered a big *No* in `go` ecosystem

2018-08-17 02:11 UTC, arush-sal commented on internal/cluster/showPath.go
> +	fmt.Println(cwd)
Can't do this as this is printing `cwd` four times for both `-i` and `-c`.
![screen shot 2018-08-17 at 6 36 49 am](https://user-images.githubusercontent.com/8846519/44242590-1022c980-a1e8-11e8-8669-66db7885fe86.png)
![screen shot 2018-08-17 at 6 37 06 am](https://user-images.githubusercontent.com/8846519/44242591-10bb6000-a1e8-11e8-9f9f-a200617c0116.png)

2018-08-17 02:11 UTC, arush-sal commented on config.yaml.example
> +   os: ubuntu
Strange! But even the latest CoreOS AMI also seems to have the same issue. It seems that we need to add a new playbook to check and install the required prerequisites so that same issue doesn't occur in future.

2018-08-17 07:54 UTC, MuellerMH commented on internal/cluster/showPath_test.go
> +			want: "/Users/onko/go/src/github.com/kubernauts/tk8/config/test.tpl",
this test was for me to check how the path system is working, removed.

2018-08-17 07:55 UTC, MuellerMH commented on internal/cluster/showPath.go
> +	fmt.Println(cwd)
removed the output.

2018-08-17 07:55 UTC, MuellerMH commented on internal/cluster/aws.go
> +	}
custom ami reader

2018-08-24 10:37 UTC, MuellerMH commented
no feature pr in master anymore

2018-08-24 10:37 UTC, closed without merging